// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'dart:async' as prefix6;
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:mobx/src/api/annotations.dart' as prefix2;
import 'package:mobx/src/api/async.dart' as prefix4;
import 'package:todo_mobx_dio_real/NetworkService.dart' as prefix3;
import 'package:todo_mobx_dio_real/todo.dart' as prefix5;
import 'package:todo_mobx_dio_real/todo_list.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'TodoList',
            r'.TodoList',
            7,
            0,
            const prefix0.JsonSerializable(),
            const <int>[2],
            const <int>[3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            const <int>[],
            1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix1.TodoList() : null},
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'_TodoList',
            r'._TodoList',
            551,
            1,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 8, 9, 13],
            const <int>[3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            const <int>[],
            2,
            {},
            {},
            {},
            -1,
            1,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'dart.core.Object with .Store',
            r'.dart.core.Object with .Store',
            583,
            2,
            const prefix0.JsonSerializable(),
            const <int>[],
            const <int>[3, 4, 5, 6, 7],
            const <int>[],
            -1,
            const {},
            const {},
            const {},
            -1,
            -1,
            const <int>[],
            const [],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'httpClient',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3, const <int>[], const []),
        r.VariableMirrorImpl(
            r'todosFuture',
            2129925,
            1,
            const prefix0.JsonSerializable(),
            -1,
            4,
            5,
            const <int>[6],
            const <Object>[prefix2.observable]),
        r.MethodMirrorImpl(r'', 64, 0, -1, 0, 0, const <int>[], const <int>[],
            const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 131074, -1, -1, 7, 7, const <int>[],
            const <int>[0], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 131074, -1, -1, 8, 8, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[1],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, -1, -1, 9, 9, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'runtimeType',
            131075,
            -1,
            -1,
            10,
            10,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(
            r'fetchTodos',
            4325378,
            1,
            -1,
            11,
            12,
            null,
            const <int>[],
            const prefix0.JsonSerializable(),
            const <Object>[prefix2.action]),
        r.MethodMirrorImpl(r'getTheTodos', 262146, 1, -1, 13, 13, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 10),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 11),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 1, 12),
        r.MethodMirrorImpl(r'', 64, 1, -1, 1, 1, const <int>[], const <int>[],
            const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'other',
            32774,
            3,
            const prefix0.JsonSerializable(),
            -1,
            14,
            14,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            5,
            const prefix0.JsonSerializable(),
            -1,
            15,
            15,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_todosFuture',
            2130022,
            12,
            const prefix0.JsonSerializable(),
            -1,
            4,
            5,
            const <int>[6],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.TodoList,
        const r.FakeType(r'._TodoList'),
        const r.FakeType(r'.dart.core.Object with .Store'),
        prefix3.NetworkService,
        const m.TypeValue<prefix4.ObservableFuture<List<prefix5.Todo>>>().type,
        prefix4.ObservableFuture,
        List,
        bool,
        String,
        int,
        Type,
        const m.TypeValue<prefix6.Future<dynamic>>().type,
        prefix6.Future,
        const m.TypeValue<void>().type,
        Object,
        Invocation
      ],
      3,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'fetchTodos': (dynamic instance) => instance.fetchTodos,
        r'getTheTodos': (dynamic instance) => instance.getTheTodos,
        r'httpClient': (dynamic instance) => instance.httpClient,
        r'todosFuture': (dynamic instance) => instance.todosFuture
      },
      {
        r'todosFuture=': (dynamic instance, value) =>
            instance.todosFuture = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
